packages:
  - 'packages/*'
  - 'apps/*'
allowBuilds:
  '@ladybugdb/core': true
  '@scarf/scarf': false
  gitnexus: true
  onnxruntime-node: true
  protobufjs: false
  sharp: true
  tree-sitter: true
  tree-sitter-c: true
  tree-sitter-c-sharp: true
  tree-sitter-cli: true
  tree-sitter-cpp: true
  tree-sitter-dart: true
  tree-sitter-go: true
  tree-sitter-java: true
  tree-sitter-javascript: true
  tree-sitter-kotlin: true
  tree-sitter-php: true
  tree-sitter-python: true
  tree-sitter-ruby: true
  tree-sitter-rust: true
  tree-sitter-swift: true
  tree-sitter-typescript: true
